### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by rhclayto** [GoogleCloudPlatform/google-fluentd#139]
Any chance that this will be packaged for FreeBSD at some point?

If not, is there any way to manually get something like this working on FreeBSD. i.e., sending system & application logs to Stackdriver Logging?

**Comment by igorpeshansky** [comment]
No, sorry, there are currently no plans to distribute a FreeBSD package or support FreeBSD. This being Ruby, you may be able to get it to work, but you'd have to build the package yourself.
