### ISSUE TITLE
Logrotate causes causes tail to stop until manual service restart

### ISSUE THREAD

**Issue by mh-bennett** [GoogleCloudPlatform/google-fluentd#142]
Occasionally, during logrotate on a GCE CentOS 7 VM, fluentd does not restart correctly, and logs are not tailed until the service is restarted. Using stock configuration of google-fluentd.

Added a sudo systemctl restart google-fluentd to the postrotate block in the google-fluentd logrotate config. Still saw the same issue. Any help appreciated ASAP - this is causing Stackdriver logging to stop on the platform entirely unless it is manually checked daily

**Comment by jkohen** [comment]
@qingling128 I remember you investigated some issues with logrotate. Could you take a look, please?

**Comment by qingling128** [comment]
@mbennett-zendesk Any chance in your environment logrotate is enabled in `/var/log` for files with suffix `.log`? We had suspicions over broken buffer files causing Fluentd to get stuck. And recently we realized Fluentd buffer files have the postfix `.log` and it can be accidentally rotated itself. That might cause issues.

A flag has been [added](https://github.com/ganmacs/fluentd/commit/358b69b49e6e4c3e98c42b4afc508290bb44239e) to customize that suffix. But it's not released yet.

If this is the cause for your case, you can do one of the following things:
- Disable the log rotation in `/var/log/google-fluentd/buffers`.
- Change the buffer path to `/var/run/google-fluentd/buffers` (We are planning to make this change in the next major release) or some other folder that does not have log rotation enabled.
- Wait for Fluentd release and google-fluentd to include the new Fluentd version, then set `path_suffix` to `.buf`.

**Comment by qingling128** [comment]
Bug seems stale for a bit.
@mh-bennett - Is this still affecting you? Did the solution work? Please reopen if the issue persists.

**Comment by gingersnapz** [comment]
What would be the best way to troubleshoot this issue? 

I have to restart the google-fluentd service every few days or so. I'm currently using the latest version, there are no error logs being shown from what I can see. I've also validated that the service is running even though no logs are being fed to Stackdriver. Test messages also do not get sent to Stackdriver using "logger". Any help is appreciated.

**Comment by igorpeshansky** [comment]
@gingersnapz, does /var/log/google-fluentd/google-fluentd.log continue to get updated? If not, the outer service process may be running, but the worker process may have crashed. Are there any errors in that log?
You might also find https://docs.fluentd.org/input/tail#logrotate-setting useful.
I assume you've already looked at the troubleshooting steps at https://cloud.google.com/logging/docs/agent/troubleshooting, and that they didn't help.

**Comment by gingersnapz** [comment]
No the log does not continue to get updated. The last and only entry in the log file before it stopped feeding to Stackdriver was something along the lines of "buffer forcefully flushed" then it wasn't updated for the two days I let it sit. I will look at the log rotation settings and see if I can figure something out. Yes I've used all of those methods of troubleshooting to no avail, unfortunately.
