### ISSUE TITLE
what is current google-fluentd consistent td-agent

### ISSUE THREAD

**Issue by zffocussss** [GoogleCloudPlatform/google-fluentd#171]
td-agent have two versions now.
v1.0 (td-agent3)
v0.12 (td-agent2)

how can I get information about google-fluentd detail?

**Comment by igorpeshansky** [comment]
What is the specific question here? The `google-fluentd` package is a fork of `td-agent` that reuses the omnibus packaging, but it's not the same package.

**Comment by zffocussss** [comment]
I want to know what can I use specific google-fluentd like specific td-agent versions

**Comment by igorpeshansky** [comment]
Yes, google-fluentd is versioned, with each version tagged on the [Releases page](https://github.com/GoogleCloudPlatform/google-fluentd/releases). We generally don't recommend installing earlier versions because they are backward-compatible, though they are available if necessary. When we do a major version bump, the previous major version will still be available under another package name.
Does this answer your questions?

**Comment by zffocussss** [comment]
no,If i want to use v0.12 (td-agent2) .what is version of google-fluentd as same as v0.12 (td-agent2)?

**Comment by zffocussss** [comment]
is there a version mapping rule between google-fluentd and original fluentd(td-agent)?

**Comment by igorpeshansky** [comment]
There is no version mapping between the two — they are different packages. It looks like you're talking about the `fluentd` gem version, however. The last version of `google-fluentd` to bundle fluentd v0.12 was [v1.5.27](https://github.com/GoogleCloudPlatform/google-fluentd/releases/tag/v1.5.27), which at this point is over 15 months old.
It would help to know why you need the older version of fluentd and what problems you encounter when using the latest agent package.

**Comment by zffocussss** [comment]
I want to the latest version of google-fluentd.
/usr/sbin/google-fluentd --version
google-fluentd 1.2.5

**Comment by zffocussss** [comment]
dpkg-query --show --showformat \
>     '${Package;-45} ${Version;-10} ${Architecture;-8} ${Status;-25}\n' \
>     google-fluentd \
>     google-fluentd-catch-all-config \
>     google-fluentd-catch-all-config-structured
google-fluentd                                1.6.5-1    amd64    install ok installed
google-fluentd-catch-all-config               0.7        all      install ok installed

**Comment by zffocussss** [comment]
what is the right version?
/usr/sbin/google-fluentd --version tell me 1.2.5
dpkg-query --show tell me google-fluentd 1.6.5-1

**Comment by igorpeshansky** [comment]
The version reported by `dpkg` is correct. The `--version` flag gives you the embedded fluentd gem version.

**Comment by zffocussss** [comment]
okay
