### ISSUE TITLE
Can google-fluentd send logs to stackdriver(default) and my own elasticsearch server?

### ISSUE THREAD

**Issue by zffocussss** [GoogleCloudPlatform/google-fluentd#177]
Hi team
           I want to collect logs and display some data on graph.but I can see below configurations on /etc/google-fluentd/google-fluentd.conf.how can I configurate to add one destination for the logs?

```
<match **>
  @type google_cloud
  buffer_chunk_limit 1M

  flush_interval 5s

  disable_retry_limit false

  retry_limit 3

  retry_wait 10

  max_retry_wait 300

  num_threads 8

  use_grpc true

  partial_success true

  enable_monitoring true
  monitoring_type prometheus

</match>
```

**Comment by igorpeshansky** [comment]
If you just want to see metrics about your logs on some graphs, you might be interested in [Logs-based metrics](https://cloud.google.com/logging/docs/logs-based-metrics/) instead.

See [Customizing agent configuration](https://cloud.google.com/logging/docs/agent/configuration#configure) for how to modify the config. You should be able to change the `match` clause to use the [out_copy](https://docs.fluentd.org/output/copy) plugin to do what you want. You may have to install additional gems for the outputs you want. Note that any outputs other than `google_cloud` are not officially supported, so you're on your own.

You may also be able to use [Stackdriver logging exports](https://cloud.google.com/logging/docs/export/) to export your logs after ingestion.
