### ISSUE TITLE
Is it possible to upgrade version of plugin gems ?

### ISSUE THREAD

**Issue by koncha99** [GoogleCloudPlatform/google-fluentd#178]
Hi,
I haven't checked the version of all plugins though, it seems that some plugins was old compared to fluentd's version.
When I used rewrite-tag-filter plugin, I noticed its version was 1.5.5 released 3 years ago.
I think its latest one can work with fluentd version this project uses.
Is that possible to upgrade these plugins ?

Thanks.

**Comment by igorpeshansky** [comment]
Yes, good idea. Stay tuned.

**Comment by koncha99** [comment]
Thank you for the quick response !

**Comment by igorpeshansky** [comment]
Your request came at just the right time — we were planning to do that anyway. :-)
This will appear in the next release.
