### ISSUE TITLE
A lot of spam in syslog

### ISSUE THREAD

**Issue by godunko-v** [GoogleCloudPlatform/google-fluentd#187]
After updating google-fluentd from **1.6.4-1** version to **google-fluentd 1.6.12-1**   on Ubuntu 18.04, we got a lot of messages in **syslog** like this:

```
collectd[1463]: parse_value: Ignoring trailing garbage ".0" after derive value. Input string was "**21.0**".
collectd[1463]: parse_value: Ignoring trailing garbage ".0" after derive value. Input string was "**780.0**".
```

I found out, that periodicity depends on stackdriver-agent config, by default every 60 Seconds and related with stackdriver-agent exec plugin:

```
<Plugin "exec">
  Exec "nobody" "/opt/stackdriver/collectd/bin/stackdriver-read_agent_logging" "curl http://localhost:24231/metrics"
</Plugin>
```

When I check this page by curl

`curl http://localhost:24231/metrics`

I just realized what data from my example equal to values on that page
Input string was "**21.0**" = _stackdriver_successful_requests_count_
Input string was "**780.0**"  = _stackdriver_ingested_entries_count_

If **stackdriver-agent** or **google-fluentd** is stopped  - there no messages like this in **syslog** but when they working together we see this messages every minute.

**Comment by godunko-v** [comment]
The main reason of this behavior is wrong type  errors. Because **google-fluentd 1.6.12-1**  version returns float values instead of integer

```
PUTVAL /agent-0/derive-request_count N:41.0
PUTVAL /agent-0/derive-log_entry_count N:156.0
```

**Comment by jkohen** [comment]
Thanks for the investigation! For our own reference, the files in question are:
https://github.com/Stackdriver/collectd/blob/master/src/read_agent_logging.in
https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/master/lib/fluent/plugin/out_google_cloud.rb
