### ISSUE TITLE
Are older debian packages not available?

### ISSUE THREAD

**Issue by lmuhlha** [GoogleCloudPlatform/google-fluentd#194]
Hi,

We recently upgraded our fleet to a new version of Ubuntu and as a result, the latest version of google-fluentd was pulled down and we ran into some issues. 
We were hoping to pin an older version, but it seems that only the latest is available at https://packages.cloud.google.com/apt/dists/google-cloud-logging-wheezy/main/binary-amd64/Packages

Is this intentional or is there a way to get older versions?

Thanks!

**Comment by igorpeshansky** [comment]
Hi, @lmuhlha. What version did you pull down, what issues did you run into, and what older version are you looking for? Older versions are not available directly from the `stable` repo, but they are archived in repos with date suffixes, which we can look up for you.

**Comment by lmuhlha** [comment]
Thanks for the quick reply. We have a puppet config set up that pulls down the stable version.
So currently, depending on when the machine was spun up, our fleet has various versions running. 
This was most likely the breaking change: https://github.com/GoogleCloudPlatform/google-fluentd/releases/tag/1.6.12 
"Update default embedded Ruby version from 2.4 to 2.5"
Our gcplogging class was reported as no longer working once people started upgrading their machines and getting 1.6.13 automatically. 
I'm working on a fix currently that would work with 1.6.13, but it would be much nicer to be able to pin a version to prevent this from happening in the future. Is there a particular reason why stable only lets you pull down latest?

**Comment by igorpeshansky** [comment]
Hmm, I'd like to understand how the embedded Ruby version in our package would affect anything outside of our package (it shouldn't change any system components). Can you please provide more details on that? Is gcplogging related to [Docker's gcplogging](https://github.com/moby/moby/blob/master/daemon/logger/gcplogs/gcplogging.go), or is it just similar naming? It may also be easier to do this through a Cloud Support case, rather than a GitHub issue, if you prefer...
The reason `stable` only contains the latest is an artifact of the release infrastructure we use. Unfortunately, it's not something that would be easy to change. Am I understanding correctly that you're looking to downgrade to [1.6.11](https://github.com/GoogleCloudPlatform/google-fluentd/releases/tag/1.6.11) while you work around the issue?

**Comment by lmuhlha** [comment]
The way we were installing the gem's ran into trouble. It was using the deprecated --no-ri --no-doc, so that had to be updated to --no-documents which required a few changes. 

Currently I'm running into this problem:  

`config error file="/etc/google-fluentd/google-fluentd.conf" error_class=Fluent::ConfigError error="no grok patterns. Check configuration, e.g. typo, configuration syntax, etc"`

But the config is the same as before / seems fine from what i can tell: 
`# Master configuration file for google-fluentd

# Include any configuration files in the config.d directory.
@include config.d/*.conf

# Do not collect fluentd's own logs to avoid infinite loops.
<match fluent.**>
  @type null
</match>

#Add the @NORMAL label to everything (needed to catch the concat'd multiline messages)
<match **>
  @type relabel
  @label @NORMAL
</match>

# Configure all sources to output to Google Cloud Logging
<label @NORMAL>
  <match **>
    @type google_cloud
    # Set the chunk limit conservatively to avoid exceeding the limit
    # of 10MB per write request.
    buffer_chunk_limit 2M
    #buffer_queue_limit 128
    flush_interval 5s
    # Use multiple threads for processing.
    num_threads 8
    # Never wait longer than 5 minutes between retries.
    max_retry_wait 300
    # Disable the limit on the number of retries (retry forever).
    disable_retry_limit
    use_metadata_service true
    project_id project-id
  </match>
</label>`

If I can at least get that working, then I should be okay with using the new version. 

Thanks again for your help!

**Comment by igorpeshansky** [comment]
That error seems to come from the `grok` parser, which isn't mentioned in the config you posted. I'm guessing it's in some file under `config.d`.
I'm happy to help you debug this, but the issue was opened to find out how to downgrade to a previous version. Are you still interested in that? If so, what version are you looking to downgrade to?

**Comment by lmuhlha** [comment]
If it's not possible to have multiple versions we can grab from https://packages.cloud.google.com/apt/dists/google-cloud-logging-wheezy/main/binary-amd64/Packages then we're just going to fix the incompatibility with the latest version and add 1.6.14 to our deb repo internally to use / have more control over. Thanks! 

I'll look a bit more into the config.d files.

**Comment by igorpeshansky** [comment]
For any given version, we can give you a direct repo link that will serve that exact version and will never be updated (by us or anyone else). This is something that will likely become more self-service for our customers in the future, but for now we are the only ones who can look up those links. Upgrading to a specific new version would then involve using a different direct link, or you could switch back to `stable`.

**Comment by dmichel1** [comment]
@igorpeshansky can we get a direct link for version `1.6.5-1` that would greatly help us right now. 

thanks

**Comment by igorpeshansky** [comment]
@dmichel1, you can install `1.6.5-1` as follows:
```bash
sudo env REPO_SUFFIX=20190316-1 bash install-logging-agent.sh
```

**Comment by igorpeshansky** [comment]
Update for folks coming here looking for older packages: as of ~March 2020, the [installation process](https://cloud.google.com/logging/docs/agent/installation) uses a different script, `add-logging-agent-repo.sh`, to add the repository with the `-all` suffix (e.g., `google-cloud-logging-buster-all`), which contains the latest version as well as the older package versions. If you are still using `install-logging-agent.sh`, you should switch — we have not changed the behavior of that script to maintain backward compatibility. See also #308.
