### ISSUE TITLE
Failed to flush the buffer GRPC::Unavailable 14:Deadline exceeded

### ISSUE THREAD

**Issue by btj** [GoogleCloudPlatform/google-fluentd#258]
Since yesterday around 2pm GMT, I'm getting `failed to flush the buffer. [...] error_class=GRPC::Unavailable error="14:Deadline Exceeded"`.

Manually creating a log entry using `gcloud logging write my-test-log "A simple entry."` does work.

**Comment by btj** [comment]
Update: I reset the VM and now it works fine again...

**Comment by bplotnick** [comment]
We also saw this: https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/393

**Comment by igorpeshansky** [comment]
Duplicate of GoogleCloudPlatform/google-fluentd#258.
