### ISSUE TITLE
google-fluentd official docker image

### ISSUE THREAD

**Issue by voxmaster** [GoogleCloudPlatform/google-fluentd#275]
Is there any chance that google-fluentd will be distributed in public Container Registry (like Docker Hub or gcr.io) to use it as a sidecar in GKE for example? Tried to find one, but all I see is only individual projects without any official support. Maybe there is an alternative way or workaround? Please share some info.

**Comment by igorpeshansky** [comment]
Yep, gcr.io/stackdriver-agents/stackdriver-logging-agent, built from the Dockerfile in this repo.
