### ISSUE TITLE
Service failed after upgrade

### ISSUE THREAD

**Issue by hylke94** [GoogleCloudPlatform/google-fluentd#308]
Since the service upgrade this morning, from version 1.8.5-1 to 1.8.5-1 (somehow), the service won't start again. Even after purging and deleting all configuration and pos files, the service start crashes. Exit-code is 203.

```
Dec 02 10:09:21 ***** systemd[1]: Starting google-fluentd.service...
-- Subject: Unit google-fluentd.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit google-fluentd.service has begun starting up.
Dec 02 10:09:21 grutte-apier-web01 systemd[21109]: google-fluentd.service: Failed to execute command: Exec format error
Dec 02 10:09:21 grutte-apier-web01 systemd[21109]: google-fluentd.service: Failed at step EXEC spawning /etc/init.d/google-fluentd: Exec format error
-- Subject: Process /etc/init.d/google-fluentd could not be executed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The process /etc/init.d/google-fluentd could not be executed and failed.
-- 
-- The error number returned by this process is 8.
Dec 02 10:09:21 grutte-apier-web01 systemd[1]: google-fluentd.service: Control process exited, code=exited status=203
Dec 02 10:09:21 grutte-apier-web01 systemd[1]: google-fluentd.service: Failed with result 'exit-code'.
Dec 02 10:09:21 grutte-apier-web01 systemd[1]: Failed to start google-fluentd.service.
-- Subject: Unit google-fluentd.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit google-fluentd.service has failed.
-- 
-- The result is RESULT.
```

**Comment by martinfriedrich** [comment]
seeing this too in our pipelines in ubuntu16 and ubuntu20

it seems that the packages contain the wrong architecture

```
default:     Get:1 http://packages.cloud.google.com/apt google-cloud-logging-focal/main amd64 google-fluentd amd64 1.8.5-1 [88.5 MB]
--
  | default:     Get:2 http://packages.cloud.google.com/apt google-cloud-logging-focal/main amd64 google-fluentd-catch-all-config all 0.7 [5740 B]
```

`Failed at step EXEC spawning /etc/init.d/google-fluentd: Exec format error`

**Comment by fjomier** [comment]
Indeed, the last deb package is broken.
It has no systemd service file and the init V script is empty.
And, as Google is not providing any previous version of this package on its APT repo (strange decision by the way), we’re stuck with that broken version.

**Comment by prasannavl** [comment]
A couple of observations: 

- It seems the repo you have is  `google-cloud-logging-focal` while the default installation from `https://cloud.google.com/logging/docs/agent/installation#agent-install-debian-ubuntu`, this should setup the repo as `google-cloud-logging-focal-all`. 
- Does removing the repo file at `/etc/apt/sources.list.d/google-cloud-logging.list` and then reinstall from the script in the docs above help?

Additionally, if that doesn't work, the previous packages are indeed also available in the format: 
> https://packages.cloud.google.com/apt/pool/google-fluentd_{version}_{hash}.deb

The latest one currently being: (1.8.4-1)
> https://packages.cloud.google.com/apt/pool/google-fluentd_1.8.4-1_amd64_9f06c46e52fafb3bd5a7b1c025dbb40fd0c62df951f1d37c845d78679beed753.deb

**Comment by fjomier** [comment]
Hi @prasannavl,

You're right, we were using the wrong repository (`google-cloud-logging-bionic`). After switching to `google-cloud-logging-bionic-all`, we got back the 1.8.4-1, and also all the other previous versions.

We got rid of the Google install script a long time ago, replaced it by manually setting the repo. I guess the repository changed in the mean time.

Thanks for you help !

**Comment by hylke94** [comment]
@prasannavl That fixes it indeed. Apparently they updated their repo url at some point...

**Comment by igorpeshansky** [comment]
@hylke94 I suspect you ended up somehow pointing at the unstable repo, which has untested builds of the future package versions… As @prasannavl says, the stable packages are in the `google-cloud-logging-{codename}-all`.

**Comment by hylke94** [comment]
@igorpeshansky Thanks for the clarification.
