### ISSUE TITLE
No way to specify GOOGLE_APPLICATION_CREDENTIALS before install

### ISSUE THREAD

**Issue by jalseth** [GoogleCloudPlatform/google-fluentd#331]
There doesn't appear to be a way to specify the `GOOGLE_APPLICATION_CREDENTIALS` environment variable before installing the deb package, so the installation always fails with on-prem servers because it attempts to start the `google-fluentd` during the install.

I've been able to hack around this by ignoring the error, inserting the variable to the `/etc/init.d/google-fluentd` script, restarting the service, and then completing the installation with `apt-get install -f`. 

This still slows down the deployment significantly as there's a series of retries before the initial install eventually fails, and makes my deployment automation much more complicated than it should be.

**Comment by aliabbasrizvi** [comment]
Not sure if this helps, but I have been able to work around this by getting credentials to the default path: `/etc/google/auth/application_default_credentials.json`. That way I do not need to set `GOOGLE_APPLICATION_CREDENTIALS `.

**Comment by igorpeshansky** [comment]
Note that the `google-fluentd` package is not designed for on-prem use, so your use case is unsupported, even if it happens to work. We make no guarantees that it won't break in the future.

That said, supplying alternate credentials *is* supported. You can indeed place the file into the default location, as long as it won't interfere with other applications, or you can set the variable appropriately in `/etc/default/google-fluentd`, which can be created prior to installation.

**Comment by igorpeshansky** [comment]
I believe the [previous comment](https://github.com/GoogleCloudPlatform/google-fluentd/issues/331#issuecomment-916565168) resolves this issue. If not, please reopen.
