### ISSUE TITLE
Can't install google-fluentd on Amazon Linux 2023

### ISSUE THREAD

**Issue by huypd6946-cowell** [GoogleCloudPlatform/google-fluentd#428]
Does anyone able to install google-fluentd on amazon linux 2023? I try many ways but not work. 
Someone can support me to resolve this?

**Comment by igorpeshansky** [comment]
Unfortunately, the agent only supports the Amazon Linux 2016.09 AMI. Neither Amazon Linux 2 nor Amazon Linux 2023 are supported. If you're in a position to open a [Google Cloud support](https://cloud.google.com/support) ticket, please feel free to file a feature request.

In the meantime, you could try running the agent in a container based off one of the [supported operating systems](https://cloud.google.com/logging/docs/agent/logging#supported_operating_systems)…
